ALTER SESSION SET CONTAINER=XEPDB1;

--PERSON TABLE
CREATE TABLE APPUSER.PERSON (
	PERSON NUMBER,
	PERSON_TOKEN VARCHAR2(1000) NOT NULL,
	USERNAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY(PERSON)
);
CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

--ACCOUNT TABLE
CREATE TABLE APPUSER.ACCOUNT (
	ACCOUNT NUMBER,
	CURRENCY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (ACCOUNT),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
);
CREATE SEQUENCE APPUSER.SQ_ACCOUNT NOCACHE;

--EXPENSE TABLE
CREATE TABLE APPUSER.EXPENSE (
	EXPENSE NUMBER,
	CATEGORY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ACCOUNT NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (EXPENSE),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	FOREIGN KEY(ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
CREATE SEQUENCE APPUSER.SQ_EXPENSE NOCACHE;

--INCOME TABLE
CREATE TABLE APPUSER.INCOME (
	INCOME NUMBER,
	CATEGORY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ACCOUNT NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (INCOME),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	FOREIGN KEY(ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
CREATE SEQUENCE APPUSER.SQ_INCOME NOCACHE;

-- CREATE FUNCTION
CREATE OR REPLACE FUNCTION APPUSER.API_TOKEN(PSECRET VARCHAR2) RETURN VARCHAR2
IS VRESULT VARCHAR2(4000);
BEGIN
	SELECT UTL_RAW.CAST_TO_VARCHAR2(UTL_I18N.STRING_TO_RAW(STANDARD_HASH(PSECRET, 'MD5'), 'AL32UTF8')) INTO VRESULT from dual;
	RETURN VRESULT;
END API_TOKEN;
/

--ALTER TABLE PERSON
--ADD CONSTRAINT unique_email UNIQUE(EMAIL);

--SELECT * FROM PERSON;
--SELECT * FROM ACCOUNT;
--SELECT * FROM EXPENSE;
--SELECT * FROM INCOME;
--ALTER TABLE APPUSER.EXPENSE MODIFY AMMOUNT NUMBER(12,6);
--ALTER TABLE APPUSER.INCOME MODIFY AMMOUNT NUMBER(12,6);
--ALTER TABLE APPUSER.ACCOUNT MODIFY AMMOUNT NUMBER(12,6);
