ALTER SESSION SET CONTAINER=XEPDB1;

--PERSON TABLE
CREATE TABLE APPUSER.PERSON (
	PERSON NUMBER,
	USERNAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY(PERSON)
);
CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

--ACCOUNT TABLE
CREATE TABLE APPUSER.ACCOUNT (
	ACCOUNT NUMBER,
	CURRENCY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (ACCOUNT),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
);
CREATE SEQUENCE APPUSER.SQ_ACCOUNT NOCACHE;

--EXPENSE TABLE
CREATE TABLE APPUSER.EXPENSE (
	EXPENSE NUMBER,
	CATEGORY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ACCOUNT NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (EXPENSE),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	FOREIGN KEY(ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
CREATE SEQUENCE APPUSER.SQ_EXPENSE NOCACHE;

--INCOME TABLE
CREATE TABLE APPUSER.INCOME (
	INCOME NUMBER,
	CATEGORY VARCHAR2(100) NOT NULL,
	AMMOUNT NUMBER(12,6) NOT NULL,
	PERSON NUMBER NOT NULL,
	ACCOUNT NUMBER NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (INCOME),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	FOREIGN KEY(ACCOUNT) REFERENCES APPUSER.ACCOUNT(ACCOUNT)
);
CREATE SEQUENCE APPUSER.SQ_INCOME NOCACHE;



--ALTER TABLE PERSON
--ADD CONSTRAINT unique_email UNIQUE(EMAIL);

--SELECT * FROM PERSON;
--SELECT * FROM ACCOUNT;
--SELECT * FROM EXPENSE;
--SELECT * FROM INCOME;
--ALTER TABLE APPUSER.EXPENSE MODIFY AMMOUNT NUMBER(12,6);
--ALTER TABLE APPUSER.INCOME MODIFY AMMOUNT NUMBER(12,6);
--ALTER TABLE APPUSER.ACCOUNT MODIFY AMMOUNT NUMBER(12,6);
